// node tools/gen-catalog.mjs -> PATTERNS.md (human/Claude-readable) + patterns.json (machine-readable)
import { listPatterns, CATEGORIES } from '../src/index.js';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const list = listPatterns();
const timings = existsSync('previews/timings.json') ? JSON.parse(readFileSync('previews/timings.json', 'utf8')).ms : {};
writeFileSync('patterns.json', JSON.stringify(list, null, 1));

const fmt = (s) => {
  const d = Array.isArray(s.default) ? s.default.join(', ') : String(s.default);
  const range = s.type === 'enum' ? s.options.join(' \\| ') : s.min !== undefined ? `${s.min} – ${s.max}` : '';
  return `| \`${s._k}\` | ${s.type} | ${d.replace(/\|/g, '\\|')} | ${range} | ${(s.label || '') + (s.help ? ' — ' + s.help : '')} |`.replace(/\n/g, ' ');
};

let md = `# Pattern catalog\n\n_Generated by \`node tools/gen-catalog.mjs\` — do not edit by hand._\n\n${list.length} patterns. Every one is seamless, deterministic per seed, and accepts any params (invalid values are clamped/replaced by defaults). Preview images: \`previews/<id>.png\`. Render time = 512×512 with 4× supersampling in Node ${process.version}.\n\n`;
for (const c of CATEGORIES) {
  md += `- **${c}**: ${list.filter((p) => p.category === c).map((p) => `[\`${p.id}\`](#${p.id})`).join(', ')}\n`;
}
for (const c of CATEGORIES) {
  md += `\n## ${c}\n`;
  for (const p of list.filter((x) => x.category === c)) {
    md += `\n### ${p.id}\n**${p.name}** — ${p.description}\n\nTags: ${p.tags.join(', ')}${timings[p.id] ? ` · ~${timings[p.id]} ms` : ''} · preview: \`previews/${p.id}.png\`\n\n| param | type | default | range / options | notes |\n|---|---|---|---|---|\n`;
    for (const [k, s] of Object.entries(p.params)) md += fmt({ ...s, _k: k }) + '\n';
  }
}
writeFileSync('PATTERNS.md', md);
console.log(`PATTERNS.md + patterns.json: ${list.length} patterns`);
