// node tools/gen-catalog.mjs (npm run catalog) -> generated from the code, never edit by hand:
//   PATTERNS.md        readable catalog: every pattern, its params, presets and preview image
//   patterns.json      the same metadata, machine-readable (listPatterns() + presets)
//   src/patterns.d.ts  TypeScript: per-pattern param interfaces, PatternId / PresetId unions
import { listPatterns, listPresets, CATEGORIES, VERSION, featureCount } from '../src/index.js';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const list = listPatterns();
const presets = listPresets();
const timings = existsSync('previews/timings.json') ? JSON.parse(readFileSync('previews/timings.json', 'utf8')).ms : {};
writeFileSync('patterns.json', JSON.stringify({ version: VERSION, patterns: list, presets }, null, 1) + '\n');

// ---------------------------------------------------------------- PATTERNS.md
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const fmtDefault = (s) => (Array.isArray(s.default) ? s.default.join(', ') : String(s.default));
const fmtRange = (s) => (s.type === 'enum' ? s.options.join(' \\| ') : s.min !== undefined ? `${s.min} – ${s.max}` : s.type === 'colors' ? `${s.minItems}–${s.maxItems} colours` : '');
let md = `# Pattern catalog (texturelib ${VERSION})

_Generated by \`npm run catalog\` (tools/gen-catalog.mjs) from the source — do not edit by hand._

${list.length} patterns, ${presets.length} presets. Every pattern is seamless, deterministic per seed, and
accepts any params (invalid values are clamped / replaced by defaults). Colour params accept
\`#rgb #rrggbb #rrggbbaa rgb() hsl() transparent\`. **scale** = the param that sets density (features
per tile). Render time = 512×512, supersample 2, Node ${process.version}. Preview images:
\`previews/<id>.jpg\` (defaults), \`previews/presets/<preset>.jpg\`, contact sheets in \`previews/sheets/\`.

Usage: \`render(id, { width, params, preset })\` — see README.md / INTEGRATION.md.

`;
for (const c of CATEGORIES) md += `- **${c}**: ${list.filter((p) => p.category === c).map((p) => `[\`${p.id}\`](#${p.id})`).join(', ')}\n`;
for (const c of CATEGORIES) {
  md += `\n## ${c}\n`;
  for (const p of list.filter((x) => x.category === c)) {
    const fc = featureCount(p.id, {});
    md += `\n### ${p.id}\n\n<img src="previews/${p.id}.jpg" width="160" align="right" alt="${p.id}">\n\n**${p.name}** — ${p.description}\n\n`;
    md += `- tags: ${p.tags.join(', ')}\n- scale: \`${p.scaleParam}\` (default tile holds ${Math.round(fc.x)}×${Math.round(fc.y)} ${fc.unit})${timings[p.id] ? `\n- render: ~${timings[p.id]} ms` : ''}\n`;
    const pr = presets.filter((x) => x.pattern === p.id);
    if (pr.length) md += `- presets: ${pr.map((x) => `\`${x.id}\``).join(', ')}\n`;
    md += `\n| param | type | default | range / options | notes |\n|---|---|---|---|---|\n`;
    for (const [k, s] of Object.entries(p.params)) {
      md += `| \`${k}\`${s.advanced ? ' ⁺' : ''} | ${s.type} | ${esc(fmtDefault(s))} | ${fmtRange(s)} | ${esc((s.label || '') + (s.help ? ' — ' + s.help : ''))} |\n`;
    }
    md += '\n<br clear="right">\n';
  }
}
md += `\n⁺ = advanced (a simple UI can hide it behind "More").\n\n## Presets\n\n| preset | pattern | name | params |\n|---|---|---|---|\n`;
for (const r of presets) md += `| \`${r.id}\` | \`${r.pattern}\` | ${esc(r.name)} | \`${esc(JSON.stringify(r.params))}\` |\n`;
writeFileSync('PATTERNS.md', md);

// ---------------------------------------------------------------- src/patterns.d.ts
const tsType = (s) => {
  switch (s.type) {
    case 'int': case 'float': return 'number';
    case 'bool': return 'boolean';
    case 'enum': return s.options.map((o) => JSON.stringify(o)).join(' | ');
    case 'color': return 'ColorString';
    case 'colors': return 'ColorString[] | string';
    case 'seed': return 'number | string';
    default: return 'string';
  }
};
let dts = `// Generated by tools/gen-catalog.mjs from the pattern schemas — do not edit by hand.
// texturelib ${VERSION}: ${list.length} patterns, ${presets.length} presets.

/** '#rgb' | '#rgba' | '#rrggbb' | '#rrggbbaa' | 'rgb(...)' | 'rgba(...)' | 'hsl(...)' | 'transparent' */
export type ColorString = string;

/** Params accepted by each pattern. All optional: missing / invalid values fall back to defaults. */
export interface PatternParams {
`;
for (const p of list) {
  dts += `  /** ${p.name} — ${p.description.replace(/\*\//g, '* /')} */\n  '${p.id}': {\n`;
  for (const [k, s] of Object.entries(p.params)) {
    const range = s.min !== undefined ? ` (${s.min}–${s.max})` : '';
    dts += `    /** ${(s.label || k).replace(/\*\//g, '')}${range}${s.help ? ' — ' + s.help.replace(/\*\//g, '') : ''} Default: ${JSON.stringify(s.default)}. */\n    ${/^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}?: ${tsType(s)};\n`;
  }
  dts += '  };\n';
}
dts += `}

export type PatternId = keyof PatternParams;
export type Category = ${CATEGORIES.map((c) => `'${c}'`).join(' | ')};
export type PresetId =\n${presets.map((r) => `  | '${r.id}'`).join('\n')};
`;
writeFileSync('src/patterns.d.ts', dts);
console.log(`PATTERNS.md + patterns.json + src/patterns.d.ts: ${list.length} patterns, ${presets.length} presets`);
