// Generated by tools/gen-catalog.mjs from the pattern schemas — do not edit by hand.
// texturelib 2.0.0: 52 patterns, 123 presets.

/** '#rgb' | '#rgba' | '#rrggbb' | '#rrggbbaa' | 'rgb(...)' | 'rgba(...)' | 'hsl(...)' | 'transparent' */
export type ColorString = string;

/** Params accepted by each pattern. All optional: missing / invalid values fall back to defaults. */
export interface PatternParams {
  /** Plain weave (tabby) — 1/1 over-under: the base of poplin, canvas, chambray and linen. Different warp/weft colours give a chambray / iridescent look; raise slubs + heather for linen. */
  'plain-weave': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–128) — Pattern repeats across the tile (1 repeat = 2 threads). Default: 16. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Warp colour Default: "#3d5a80". */
    warp?: ColorString;
    /** Weft colour Default: "#e0e6ee". */
    weft?: ColorString;
  };
  /** Twill — Diagonal-rib weave. 2/2 = gabardine/serge, 3/1 = denim/drill, 2/1 = chino. S or Z diagonal. */
  'twill': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 8. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Over (warp up) (1–6) Default: 2. */
    over?: number;
    /** Under (warp down) (1–6) Default: 2. */
    under?: number;
    /** Diagonal — Z rises to the right, S to the left. Default: "Z". */
    direction?: "Z" | "S";
    /** Warp colour Default: "#4a3f35". */
    warp?: ColorString;
    /** Weft colour Default: "#b9a88f". */
    weft?: ColorString;
  };
  /** Satin — Long floats with scattered interlacings: a smooth, lustrous face. Regular satin needs a move number coprime to the shaft count, so 6 shafts is not offered. */
  'satin': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 6. */
    repeats?: number;
    /** Yarn gap (0–0.5) Default: 0.03. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) Default: 0.15. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the floats. Default: 0.7. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Shafts Default: 5. */
    shafts?: 5 | 7 | 8 | 10 | 12;
    /** Face Default: "warp". */
    face?: "warp" | "weft";
    /** Warp colour Default: "#7b1e3a". */
    warp?: ColorString;
    /** Weft colour Default: "#5a1429". */
    weft?: ColorString;
  };
  /** Basket / hopsack / oxford — Plain weave with k threads acting as one (2 = hopsack; white weft on a coloured warp = oxford cloth). */
  'basket-weave': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 6. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Threads per group (2–6) Default: 2. */
    group?: number;
    /** Warp Default: "#e7dcc5". */
    warp?: ColorString;
    /** Weft Default: "#8a9a7b". */
    weft?: ColorString;
  };
  /** Herringbone twill — 2/2 twill whose diagonal reverses every N ends with a half-step offset ("broken" twill), giving the classic fish-bone zigzag. */
  'herringbone': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–32) Default: 3. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) Default: 0.25. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Ends per band (2–32) Default: 8. */
    band?: number;
    /** Broken reversal — Offset the twill at each reversal (real herringbone). Off = plain zigzag. Default: true. */
    broken?: boolean;
    /** Warp Default: "#2b2b2b". */
    warp?: ColorString;
    /** Weft Default: "#cfc8b8". */
    weft?: ColorString;
  };
  /** Houndstooth — Colour-and-weave effect: 2/2 twill with 4 dark / 4 light in both warp and weft. Band 2 = puppytooth, band 8 = large dogtooth. Use style=flat for a crisp printed version. */
  'houndstooth': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–32) Default: 4. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Threads per colour band (1–16) Default: 4. */
    band?: number;
    /** Dark, light Default: ["#151515","#f2efe6"]. */
    colors?: ColorString[] | string;
  };
  /** Pick-and-pick / sharkskin — 2/2 twill with alternating 1 dark / 1 light warp and weft — the stepped sharkskin texture of suiting. */
  'pick-and-pick': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 12. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Dark, light Default: ["#2d3440","#a9b1bc"]. */
    colors?: ColorString[] | string;
  };
  /** Glen check / Prince of Wales — 2/2 twill alternating a houndstooth block (4&4) with a hairline block (2&2) in warp and weft; optional coloured overcheck. */
  'glen-check': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–16) Default: 2. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Dark, light Default: ["#1f1f1f","#ece8dd"]. */
    colors?: ColorString[] | string;
    /** Overcheck Default: true. */
    overcheck?: boolean;
    /** Overcheck colour Default: "#2f5e9e". */
    overcheckColor?: ColorString;
  };
  /** Gingham — Plain weave, equal coloured and white bands in warp and weft; the crossings of colour × white give the characteristic mid-tone. Use style=flat at small sizes for a print-style check. */
  'gingham': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–32) Default: 4. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Threads per band (1–32) Default: 6. */
    band?: number;
    /** Colour, ground Default: ["#c8102e","#ffffff"]. */
    colors?: ColorString[] | string;
  };
  /** Tartan / plaid (threadcount) — Renders any tartan from a threadcount like "K4 R24 K24 Y4" (letters = colours, numbers = threads). Symmetric setts mirror about the pivots. Woven in 2/2 twill so crossing blocks blend like real cloth; raise "Brushed fuzz" for flannel. */
  'tartan': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–16) — Setts across the tile. Default: 1. */
    repeats?: number;
    /** Yarn gap (0–0.5) Default: 0.06. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Sett Default: "black-watch". */
    preset?: "black-watch" | "simple-green" | "four-colour" | "buffalo-check" | "red-stewart-style" | "camel-check-style" | "grey-flannel-style" | "madras-style" | "custom";
    /** Threadcount (when sett = custom) — Letters: K W R DR B DB LB A G DG LG Y N LN P T O C M S CA, or #rrggbb/N Default: "K4 R24 K24 Y4". */
    threadcount?: string;
    /** Symmetric sett — Mirror the threadcount about its pivots (most tartans). Default: true. */
    symmetric?: boolean;
    /** Thread scale (0.1–4) — Multiplies every count: smaller = fewer, thicker threads per sett. Default: 0.5. */
    countScale?: number;
  };
  /** Denim — 3/1 right-hand (Z) twill with more ends than picks (steep twill line), ring-spun indigo warp with slubs and tone variation, ecru weft, optional fade/wash. */
  'denim': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 16. */
    repeats?: number;
    /** Yarn gap (0–0.5) Default: 0.08. */
    yarnGap?: number;
    /** Irregularity (0–1) Default: 0.7. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) Default: 0.35. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Twill direction — Z = right-hand (most jeans), S = left-hand. Default: "Z". */
    direction?: "Z" | "S";
    /** Indigo warp Default: "#1f3561". */
    indigo?: ColorString;
    /** Weft Default: "#d9d2c0". */
    weft?: ColorString;
    /** Wash / fade (0–1) — Low-frequency fading and whiskering. Default: 0.35. */
    wash?: number;
  };
  /** Tweed (Donegal / Harris) — Heathered woollen yarns in a 2/2 twill or herringbone, flecked with coloured neps (Donegal). Rough, hairy, multi-tone. */
  'tweed': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–48) Default: 12. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) Default: 0.6. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) Default: 0.4. */
    slub?: number;
    /** Heather (0–1) Default: 0.6. */
    heather?: number;
    /** Brushed fuzz (0–1) Default: 0.15. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Weave Default: "twill". */
    weave?: "twill" | "herringbone" | "plain";
    /** Warp Default: "#5b5346". */
    warp?: ColorString;
    /** Weft Default: "#8a7d66". */
    weft?: ColorString;
    /** Neps (flecks) (0–1) — Density of coloured flecks. Default: 0.35. */
    neps?: number;
    /** Fleck colours Default: ["#c8553d","#f2d0a4","#3c6e71","#e8c547"]. */
    nepColors?: ColorString[] | string;
  };
  /** Custom weave draft — Any dobby structure from a draft string: rows = picks separated by "/", 1 = warp up. Colour orders as colour lists with thread counts. Presets include waffle, bird's-eye and diamond twill. */
  'weave-draft': {
    /** Style — fabric = shaded 3D yarns; flat = solid colour per crossing (prints, pixel art); draft = black/white weave draft Default: "fabric". */
    style?: "fabric" | "flat" | "draft";
    /** Repeats (1–64) Default: 4. */
    repeats?: number;
    /** Yarn gap (0–0.5) — Fraction of each thread cell left open between yarns. Default: 0.12. */
    yarnGap?: number;
    /** Irregularity (0–1) — Per-yarn tone and thickness variation. Default: 0.35. */
    irregularity?: number;
    /** Fibre twist (0–1) — Strength of the twisted-fibre striation on each yarn. Default: 0.5. */
    twist?: number;
    /** Sheen (0–1) — Glossy highlight along the yarns (silk/satin ≈ 0.6). Default: 0.08. */
    sheen?: number;
    /** Slubs (0–1) — Thick-and-thin yarn (linen, raw silk). Default: 0.15. */
    slub?: number;
    /** Heather (0–1) — Mottled multi-tone fibres (marl / melange yarn). Default: 0. */
    heather?: number;
    /** Brushed fuzz (0–1) — Brushed / napped surface that softens the weave (flannel, brushed cotton). Default: 0. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
    /** Draft rows — e.g. "1100/0110/0011/1001" = 2/2 twill (max 64×64) Default: "11100/01110/00111/10011/11001". */
    draft?: string;
    /** Warp colour order Default: ["#264653","#e9c46a"]. */
    warpColors?: ColorString[] | string;
    /** Warp counts — Threads per colour, space separated (cycled). Default: "6 2". */
    warpCounts?: string;
    /** Weft colour order Default: ["#f4f1de"]. */
    weftColors?: ColorString[] | string;
    /** Weft counts Default: "1". */
    weftCounts?: string;
  };
  /** Knit stitches — Stockinette/jersey, garter, ribs, seed, moss, basketweave, welting, diamond brocade — interlocking V stitches and purl bumps with real depth (purl columns recede in ribs). */
  'knit': {
    /** Stitches across tile (2–256) — Higher = finer knit. Default: 16. */
    stitchesAcross?: number;
    /** Rows per stitch width (0.6–2.5) — Row/stitch gauge ratio (≈30 rows / 22 sts per 10 cm). Default: 1.36. */
    gauge?: number;
    /** Yarn thickness (0.14–0.34) — Thicker yarn closes the gaps between loops. Default: 0.25. */
    yarnRadius?: number;
    /** Irregularity (0–1) — Stitch-to-stitch tone variation (hand-knit look). Default: 0.4. */
    irregularity?: number;
    /** Fibre fuzz (0–1) — Ply striations and hairiness of the yarn. Default: 0.35. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 3. */
    seed?: number | string;
    /** Stitch pattern Default: "stockinette". */
    stitch?: "stockinette" | "reverse-stockinette" | "garter" | "rib-1x1" | "rib-2x2" | "rib-3x1" | "seed" | "moss" | "basketweave" | "broken-rib" | "welting" | "diamond-brocade";
    /** Yarn colour Default: "#b23a48". */
    color?: ColorString;
  };
  /** Fair Isle / jacquard knit — Stockinette colourwork from a chart: rows separated by "/", digits index the palette (0 = background). Built-in charts: bands, snowflake, hearts, trees, diamonds… */
  'fair-isle': {
    /** Stitches across tile (2–256) Default: 24. */
    stitchesAcross?: number;
    /** Rows per stitch width (0.6–2.5) — Row/stitch gauge ratio (≈30 rows / 22 sts per 10 cm). Default: 1.36. */
    gauge?: number;
    /** Yarn thickness (0.14–0.34) — Thicker yarn closes the gaps between loops. Default: 0.25. */
    yarnRadius?: number;
    /** Irregularity (0–1) — Stitch-to-stitch tone variation (hand-knit look). Default: 0.4. */
    irregularity?: number;
    /** Fibre fuzz (0–1) — Ply striations and hairiness of the yarn. Default: 0.35. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 3. */
    seed?: number | string;
    /** Chart Default: "fair-isle-band". */
    chart?: "none" | "diamonds" | "zigzag" | "fair-isle-band" | "snowflake" | "hearts" | "trees" | "checks" | "stripes" | "custom";
    /** Custom chart — Rows of digits separated by "/" (max 128×128). Default: "0110/1001/1001/0110". */
    customChart?: string;
    /** Palette (0,1,2,3…) Default: ["#f1ebdd","#9b1d20","#1d3557","#3a6b35"]. */
    colors?: ColorString[] | string;
  };
  /** Cable knit (aran) — Rope cables (2 strands) or braids (3 strands) of stockinette crossing every N rows, raised over a reverse-stockinette or seed-stitch ground, with depth shading and cast shadows. */
  'cable-knit': {
    /** Stitches across tile (8–256) Default: 24. */
    stitchesAcross?: number;
    /** Rows per stitch width (0.6–2.5) — Row/stitch gauge ratio (≈30 rows / 22 sts per 10 cm). Default: 1.36. */
    gauge?: number;
    /** Yarn thickness (0.14–0.34) Default: 0.27. */
    yarnRadius?: number;
    /** Irregularity (0–1) — Stitch-to-stitch tone variation (hand-knit look). Default: 0.4. */
    irregularity?: number;
    /** Fibre fuzz (0–1) — Ply striations and hairiness of the yarn. Default: 0.35. */
    fuzz?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 3. */
    seed?: number | string;
    /** Cable type — mixed = rope and braid panels alternating (aran sweater). Default: "rope". */
    cable?: "rope" | "braid" | "mixed";
    /** Rows between crossings (4–16) Default: 6. */
    crossEvery?: number;
    /** Ground stitches each side (1–6) Default: 2. */
    purlBetween?: number;
    /** Ground stitch Default: "reverse-stockinette". */
    ground?: "reverse-stockinette" | "seed";
    /** Yarn colour Default: "#e8dcc4". */
    color?: ColorString;
  };
  /** Corduroy — Rounded pile wales separated by grooves where the ground weave shows; fine vertical pile fibres with a velvety sheen on the wale shoulders. Wide wale ≈ 8, needlecord ≈ 24 per tile. */
  'corduroy': {
    /** Wales across (2–128) Default: 12. */
    wales?: number;
    /** Groove width (0.04–0.5) — Fraction of each wale that is groove. Default: 0.2. */
    groove?: number;
    /** Colour Default: "#8a5a2b". */
    color?: ColorString;
    /** Pile texture (0–1) Default: 0.6. */
    pile?: number;
    /** Sheen (0–1) — Velvet highlight across each wale. Default: 0.5. */
    sheen?: number;
    /** Wear (0–1) — Low-frequency crushing / fading of the pile. Default: 0.2. */
    wear?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 31. */
    seed?: number | string;
  };
  /** Velvet / crushed velvet — Dense short pile: smooth colour with soft shimmering highlights where the pile changes direction. Raise "crush" for crushed / panne velvet. */
  'velvet': {
    /** Colour Default: "#5b1a3a". */
    color?: ColorString;
    /** Crush scale (1–16) — Number of crush patches across. Default: 3. */
    scale?: number;
    /** Crush (0–1) — Strength of the light/dark patches. Default: 0.55. */
    crush?: number;
    /** Sheen (0–1) Default: 0.6. */
    sheen?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 41. */
    seed?: number | string;
  };
  /** Quilted / padded / puffer — Puffy padded cells (diamond, square or puffer channels) with dashed stitch seams; lit from the top-left from the real height field, with a nylon or cotton surface. */
  'quilted': {
    /** Layout Default: "diamond". */
    layout?: "diamond" | "square" | "channel";
    /** Cells across (1–32) Default: 4. */
    cells?: number;
    /** Puffiness (0–1) Default: 0.8. */
    puff?: number;
    /** Fabric Default: "#2c2c34". */
    color?: ColorString;
    /** Stitch thread Default: "#9a9aa6". */
    stitch?: ColorString;
    /** Surface — nylon = ripstop grid + sheen; satin = glossy; cotton = matte weave. Default: "nylon". */
    surface?: "nylon" | "cotton" | "satin";
    /** Stitches per seam (0 = none) (0–40) Default: 9. */
    dashes?: number;
  };
  /** Mesh / fishnet / tulle — Open net of round, twisted yarn with knots at the crossings, casting a soft shadow on the backing. Set backing to "transparent" for a see-through net. Diamond fishnet, square net or hexagonal tulle. */
  'mesh': {
    /** Net shape Default: "diamond". */
    layout?: "diamond" | "square" | "hex";
    /** Openings across (2–64) Default: 6. */
    cells?: number;
    /** Yarn thickness (cell units) (0.02–0.3) Default: 0.09. */
    yarn?: number;
    /** Knot size (0–1) Default: 0.5. */
    knots?: number;
    /** Yarn Default: "#141414". */
    color?: ColorString;
    /** Backing — Use "transparent" for a see-through net. Default: "#e0b49a". */
    backing?: ColorString;
    /** Shadow on backing (0–1) Default: 0.5. */
    shadow?: number;
  };
  /** Sequins / paillettes — Overlapping metallic discs in staggered rows, each tilted and slightly cupped so it mirrors a studio light differently; centre hole with thread, bevelled rim, shadows from the sequin above. Several colours = mixed sequins. */
  'sequins': {
    /** Sequins across (2–96) Default: 12. */
    cells?: number;
    /** Sequin colours (random mix) Default: ["#c9a227"]. */
    colors?: ColorString[] | string;
    /** Sparkle (0–1) Default: 0.6. */
    sparkle?: number;
    /** Tilt variation (0–1) Default: 0.5. */
    tilt?: number;
    /** Base fabric Default: "#1a1a1a". */
    fabric?: ColorString;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 33. */
    seed?: number | string;
  };
  /** Cross-stitch / embroidery — Aida cloth with its woven blocks and holes; chart digits (1-9) are stitched as X crosses of two-strand twisted floss in palette colours, 0 = empty. Pixel-art friendly. */
  'cross-stitch': {
    /** Chart Default: "heart". */
    chart?: "heart" | "diamonds" | "border" | "flower" | "strawberry" | "custom";
    /** Custom chart — Rows of digits separated by "/" (0 = empty, max 64×64). Default: "0110/1111/0110". */
    customChart?: string;
    /** Chart repeats (1–32) Default: 3. */
    repeats?: number;
    /** Aida Default: "#efe7d6". */
    fabric?: ColorString;
    /** Thread palette (1,2,3…) Default: ["#b3202a","#2f6d3a","#1f3b73","#d9a21b"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 35. */
    seed?: number | string;
  };
  /** Eyelet lace (broderie anglaise) — Cotton lawn with satin-stitched eyelet flowers: petal and round holes with raised, radially stitched rims and tiny dot eyelets between. Set backing to "transparent" for real see-through holes. */
  'eyelet-lace': {
    /** Flowers across (1–24) Default: 4. */
    cells?: number;
    /** Petals (4–9) Default: 6. */
    petals?: number;
    /** Hole size (0.2–1) Default: 0.5. */
    holeSize?: number;
    /** Cloth & thread Default: "#f7f5ef". */
    color?: ColorString;
    /** Backing — What shows through the holes; "transparent" for see-through. Default: "#2a3550". */
    backing?: ColorString;
    /** Dot eyelets between flowers Default: true. */
    dots?: boolean;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 43. */
    seed?: number | string;
  };
  /** Shibori / tie-dye — Resist-dye looks on woven cotton: itajime (clamped shapes + fold lines), arashi (pole-wrapped diagonal storm lines), kumo (spider-web bound circles), tie-dye spiral. Dye wicks along the weave, so edges feather along warp and weft. */
  'shibori': {
    /** Technique Default: "itajime". */
    style?: "itajime" | "arashi" | "kumo" | "spiral";
    /** Repeats (1–32) Default: 3. */
    cells?: number;
    /** Itajime shape Default: "square". */
    shape?: "square" | "circle" | "triangle";
    /** Dye bleed (0–1) Default: 0.5. */
    bleed?: number;
    /** Dye, cloth Default: ["#1b2a4a","#f2efe8"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 37. */
    seed?: number | string;
  };
  /** Stripes — Any number of coloured bands with relative widths, horizontal/vertical/diagonal, optionally wavy. Pinstripe: widths "1 14". Breton: "1 1.4". Soft = blurred band edges. */
  'stripes': {
    /** Band colours (cycled) Default: ["#1b2a49","#f4f1ea"]. */
    colors?: ColorString[] | string;
    /** Relative widths — Space-separated, one per band (cycled to match colours). Default: "1 1". */
    widths?: string;
    /** Direction Default: "horizontal". */
    direction?: "horizontal" | "vertical" | "diagonal" | "anti-diagonal" | "shallow" | "steep";
    /** Repeats (1–256) Default: 8. */
    repeats?: number;
    /** Wave amplitude (0–2) — In stripe-repeat units; 0 = straight. Default: 0. */
    wave?: number;
    /** Waves across (1–32) Default: 2. */
    waveFreq?: number;
    /** Soft edges (0–1) Default: 0. */
    soft?: number;
  };
  /** Checkerboard — Two-colour checks, square or diagonal (harlequin diamonds). Cell count is forced even so it tiles. */
  'checkerboard': {
    /** Cells across (even) (2–256) Default: 8. */
    cells?: number;
    /** Colours Default: ["#111111","#f2f2f2"]. */
    colors?: ColorString[] | string;
    /** Diagonal (harlequin) Default: false. */
    diagonal?: boolean;
  };
  /** Polka dots & tossed motifs — Dots, stars, hearts, flowers, leaves, moons… in textile repeat layouts: block, half-drop, brick or tossed (random, non-overlapping). Optional outline and flower centres make ditsy florals. */
  'dots': {
    /** Repeat layout Default: "half-drop". */
    layout?: "block" | "half-drop" | "brick" | "tossed";
    /** Motif Default: "circle". */
    shape?: "circle" | "ring" | "square" | "diamond" | "cross" | "star" | "heart" | "flower" | "triangle" | "hexagon" | "teardrop" | "moon" | "leaf";
    /** Cells across (2–128) Default: 8. */
    cells?: number;
    /** Motif radius (cell units) (0.05–0.5) Default: 0.28. */
    size?: number;
    /** Size variation (0–1) Default: 0. */
    sizeJitter?: number;
    /** Random rotation Default: false. */
    rotate?: boolean;
    /** Background — "transparent" for motifs only. Default: "#f6efe2". */
    background?: ColorString;
    /** Motif colours (random pick) Default: ["#c1272d"]. */
    colors?: ColorString[] | string;
    /** Outline width (cell units) (0–0.1) Default: 0. */
    outline?: number;
    /** Outline colour Default: "#1d1d1d". */
    outlineColor?: ColorString;
    /** Centre dot colour — E.g. yellow flower centres. "transparent" = none. Default: "transparent". */
    centerColor?: ColorString;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 5. */
    seed?: number | string;
  };
  /** Chevron / zigzag — Zigzag bands. Band count is rounded to a multiple of the colour count so colours tile. Rounded = soft wave zigzag. */
  'chevron': {
    /** Band colours Default: ["#264653","#2a9d8f","#e9c46a","#f4a261","#e76f51"]. */
    colors?: ColorString[] | string;
    /** Bands (vertical) (1–128) Default: 10. */
    bands?: number;
    /** Zigzags across (1–64) Default: 4. */
    zigs?: number;
    /** Amplitude (bands) (0–8) Default: 1.5. */
    amplitude?: number;
    /** Rounded peaks (0–1) Default: 0. */
    rounded?: number;
  };
  /** Argyle — Alternating diamonds on a ground with thin diagonal overcheck lines (dashed option, like the stitched original). */
  'argyle': {
    /** Diamonds across (even) (2–64) Default: 4. */
    cols?: number;
    /** Diamond rows (even) (2–64) Default: 2. */
    rows?: number;
    /** Diamond A, diamond B, ground Default: ["#5b2333","#2e4057","#c9b79c"]. */
    colors?: ColorString[] | string;
    /** Overcheck line Default: "#f2e8cf". */
    lineColor?: ColorString;
    /** Line width (uv) (0–0.05) Default: 0.012. */
    lineWidth?: number;
    /** Dashed overcheck Default: false. */
    dashed?: boolean;
  };
  /** Hexagon / honeycomb — Pointy-top hex grid. Vertical rows are chosen so hexes are within a few % of regular on a square tile. Cells, outline-only or bevelled tiles. */
  'honeycomb': {
    /** Hexes across (1–128) Default: 8. */
    cells?: number;
    /** Style Default: "cells". */
    style?: "cells" | "lines" | "bevel";
    /** Line width (hex units) (0–0.4) Default: 0.06. */
    line?: number;
    /** Line / gap colour Default: "#1d1d24". */
    background?: ColorString;
    /** Cell colours (random) Default: ["#f2b134","#f7c75e","#e89f1f","#fad681"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 2. */
    seed?: number | string;
  };
  /** Truchet tiles — Smith quarter-circle tiles (2-colourable: colour = inside ⊕ orientation ⊕ parity), 10-PRINT maze, or triangle tiles. */
  'truchet': {
    /** Variant Default: "arcs". */
    variant?: "arcs" | "maze" | "triangles";
    /** Tiles across (even) (2–128) Default: 10. */
    cells?: number;
    /** Two-colour fill Default: true. */
    fill?: boolean;
    /** Line width (tile units) (0–0.5) Default: 0.08. */
    lineWidth?: number;
    /** Colour A, B, line Default: ["#0f4c5c","#f6e7cb","#e36414"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 11. */
    seed?: number | string;
  };
  /** Seigaiha / scales — Overlapping concentric half-circles (Japanese wave pattern). Rings alternate through the palette. */
  'seigaiha': {
    /** Scales across (1–64) Default: 6. */
    cells?: number;
    /** Rings per scale (1–12) Default: 4. */
    rings?: number;
    /** Ring colours (outer → inner) Default: ["#1d3557","#f1faee","#457b9d","#f1faee"]. */
    colors?: ColorString[] | string;
    /** Outline (scale units) (0–0.2) Default: 0.03. */
    outline?: number;
    /** Outline colour Default: "#1d3557". */
    outlineColor?: ColorString;
  };
  /** Ogee lattice — Interlocking onion shapes. Exact two-family tiling because sin²(πy) + sin²(π(y+½)) = 1. Optional inner outline and centre dot. */
  'ogee': {
    /** Shapes across (1–64) Default: 4. */
    cols?: number;
    /** Shapes down (1–64) Default: 3. */
    rows?: number;
    /** Family A, family B Default: ["#e9d8a6","#94d2bd"]. */
    colors?: ColorString[] | string;
    /** Outline (cell units) (0–0.2) Default: 0.03. */
    line?: number;
    /** Outline Default: "#005f73". */
    lineColor?: ColorString;
    /** Inner outline inset (0 = off) (0–0.4) Default: 0.12. */
    inset?: number;
    /** Centre dot size (0–0.2) Default: 0. */
    dot?: number;
  };
  /** Islamic star (Hankin) — Hankin's polygons-in-contact: rays leave each edge midpoint at a contact angle and meet inside the tile. 4.8.8 tiling gives 8-point stars, 6.6.6 gives 6-point stars (hex rows fitted to the square tile), 4.4.4.4 gives crosses. */
  'islamic-star': {
    /** Underlying tiling Default: "4.8.8". */
    tiling?: "4.8.8" | "4.4.4.4" | "6.6.6";
    /** Contact angle (deg) (20–85) Default: 67.5. */
    angle?: number;
    /** Repeats (1–32) Default: 2. */
    repeats?: number;
    /** Strap width (cell units) (0.002–0.15) Default: 0.035. */
    width?: number;
    /** Style Default: "strap". */
    style?: "line" | "strap";
    /** Ground, strap, strap edge Default: ["#0b3954","#f4d35e","#0b3954"]. */
    colors?: ColorString[] | string;
  };
  /** Terrazzo — Irregular stone chips at two scales plus fine grit on a speckled ground, with subtle per-chip polish variation. */
  'terrazzo': {
    /** Large chips across (1–64) Default: 7. */
    density?: number;
    /** Chip size (0.05–0.5) Default: 0.32. */
    chipSize?: number;
    /** Ground Default: "#ece6dc". */
    background?: ColorString;
    /** Chip colours Default: ["#c75d3c","#2f5d62","#e3b23c","#9aa5a1","#3d3b3c"]. */
    colors?: ColorString[] | string;
    /** Fine grit (0–1) Default: 0.5. */
    grit?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 8. */
    seed?: number | string;
  };
  /** Halftone screen — Screen of dots, lines or squares whose size follows a periodic noise / wave / radial field. Screen angles use integer lattice vectors so the tile stays seamless. */
  'halftone': {
    /** Dots across (4–256) Default: 24. */
    cells?: number;
    /** Screen angle Default: "45°". */
    angle?: "0°" | "45°" | "26.6°" | "18.4°";
    /** Dot shape Default: "circle". */
    dot?: "circle" | "line" | "square" | "diamond";
    /** Tone field Default: "noise". */
    field?: "noise" | "waves" | "radial" | "flat";
    /** Tone (flat field) (0–1) Default: 0.5. */
    tone?: number;
    /** Field frequency (1–16) Default: 2. */
    scale?: number;
    /** Contrast (0.2–4) Default: 1.4. */
    contrast?: number;
    /** Paper, ink Default: ["#f7f1e3","#e63946"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 4. */
    seed?: number | string;
  };
  /** Topographic contours — Iso-lines of a periodic fbm field with constant on-screen width (gradient-normalised), thicker index lines every Nth level; optional hypsometric colour fill. */
  'contour-lines': {
    /** Levels (2–64) Default: 14. */
    levels?: number;
    /** Field frequency (1–16) Default: 2. */
    scale?: number;
    /** Line width (px @512) (0.3–6) Default: 1.6. */
    lineWidth?: number;
    /** Index line every (0–20) Default: 5. */
    indexEvery?: number;
    /** Hypsometric fill Default: false. */
    fill?: boolean;
    /** Ground, line Default: ["#f3efe0","#7a5c3e"]. */
    colors?: ColorString[] | string;
    /** Fill ramp Default: ["#2b5f4a","#7da36b","#e6d8a6","#c58b4e","#f4efe6"]. */
    fillColors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 6. */
    seed?: number | string;
  };
  /** Bricks / tiles — Running, stack, Flemish or basket-weave bond with recessed mortar; every brick has its own tone, noisy pitted surface and slightly chipped edges, plus a bevelled height map (good for normal maps). */
  'bricks': {
    /** Bond Default: "running". */
    bond?: "running" | "stack" | "flemish" | "basket";
    /** Bricks per row (1–64) Default: 4. */
    cols?: number;
    /** Rows (even for running) (2–128) Default: 8. */
    rows?: number;
    /** Mortar (brick-height units) (0–0.3) Default: 0.06. */
    mortar?: number;
    /** Brick colours Default: ["#9c4a33","#b05a3c","#8a3f2c","#a8553b"]. */
    colors?: ColorString[] | string;
    /** Mortar Default: "#cfc6b8". */
    mortarColor?: ColorString;
    /** Surface noise (0–1) Default: 0.5. */
    roughness?: number;
    /** Edge chipping (0–1) Default: 0.4. */
    chipping?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 9. */
    seed?: number | string;
  };
  /** Grid paper (graph / dot / isometric) — Graph paper with minor and major lines, dot grid, or isometric (triangular) grid — backgrounds for type specimens, blueprints and notebooks. Lines keep a constant pixel width at any size. */
  'grid-paper': {
    /** Style Default: "lines". */
    style?: "lines" | "dots" | "isometric";
    /** Cells across (2–256) Default: 16. */
    cells?: number;
    /** Major line every (0 = none) (0–16) Default: 4. */
    majorEvery?: number;
    /** Line width (px @512) (0.3–6) Default: 1. */
    lineWidth?: number;
    /** Paper, minor line, major line Default: ["#f7f5ee","#b9d4e8","#6f9fc8"]. */
    colors?: ColorString[] | string;
  };
  /** Fractal noise (fbm / ridged / turbulence) — Periodic Perlin/value fbm with optional domain warp, mapped through a colour ramp. Use output=height for height maps. */
  'noise': {
    /** Basis Default: "perlin". */
    basis?: "perlin" | "value";
    /** Mode Default: "fbm". */
    mode?: "fbm" | "ridged" | "turbulence";
    /** Base frequency (integer) (1–64) Default: 4. */
    frequency?: number;
    /** Octaves (1–10) Default: 6. */
    octaves?: number;
    /** Gain (persistence) (0.1–0.9) Default: 0.5. */
    gain?: number;
    /** Domain warp (0–1) Default: 0. */
    warp?: number;
    /** Contrast (0.2–4) Default: 1. */
    contrast?: number;
    /** Colour ramp Default: ["#04202f","#0b4f6c","#20a4c3","#c9f1f5"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 1. */
    seed?: number | string;
  };
  /** Marble — Turbulence-displaced veins (Perlin marble) at two scales: bold main veins with a soft halo and a sharp core, a web of fine hairline veins, and cloudy tonal drifts. Presets: Carrara, Calacatta gold, Nero Marquina, verde. */
  'marble': {
    /** Base Default: "#eeebe5". */
    base?: ColorString;
    /** Vein Default: "#5d5a57". */
    vein?: ColorString;
    /** Cloud tint Default: "#c9b8a0". */
    tint?: ColorString;
    /** Vein halo / accent — Colour of the soft halo around main veins (gold for Calacatta). Default: "#b08d57". */
    accent?: ColorString;
    /** Main veins (1–16) Default: 1. */
    veins?: number;
    /** Turbulence (0–6) Default: 1. */
    turbulence?: number;
    /** Vein sharpness (1–30) Default: 5. */
    sharpness?: number;
    /** Fine veins (0–1) Default: 0.5. */
    fine?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 12. */
    seed?: number | string;
  };
  /** Granite / speckled stone — Interlocking mineral grains (Voronoi crystals) in a weighted palette — feldspar, quartz, mica — with polished glints and slight clouding. */
  'granite': {
    /** Grains across (8–256) Default: 48. */
    grain?: number;
    /** Minerals (first = most common) Default: ["#c9c2b8","#8c857c","#3b3836","#e9e4dc","#a4704f"]. */
    colors?: ColorString[] | string;
    /** Contrast (0.3–2) Default: 1. */
    contrast?: number;
    /** Mica glints (0–1) Default: 0.4. */
    glints?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 23. */
    seed?: number | string;
  };
  /** Wood planks / floorboards — Flat-sawn boards with cathedral growth-ring arches, wobbling grain, pore streaks, optional knots; per-board tone, bevelled seams and staggered butt joints like a real floor. */
  'wood': {
    /** Planks across (1–32) Default: 4. */
    planks?: number;
    /** Joints per tile height (1–12) — Board ends per column; staggered between columns. Default: 2. */
    plankLength?: number;
    /** Ring density (1–40) Default: 9. */
    rings?: number;
    /** Grain wobble (0–3) Default: 0.8. */
    wobble?: number;
    /** Knots (0–1) Default: 0.2. */
    knots?: number;
    /** Light, mid, dark Default: ["#e1b382","#c08552","#8c5a3c"]. */
    colors?: ColorString[] | string;
    /** Seam width (uv) (0–0.02) Default: 0.004. */
    seam?: number;
    /** Board tone variation (0–1) Default: 0.5. */
    variation?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 21. */
    seed?: number | string;
  };
  /** Parquet (herringbone / chevron / basket) — Wooden parquet floors: herringbone (planks k:1 at right angles), chevron (mitred V columns), basket (square blocks of parallel slats) or straight staggered planks. Every plank gets its own grain and tone. */
  'parquet': {
    /** Layout Default: "herringbone". */
    layout?: "herringbone" | "chevron" | "basket" | "straight";
    /** Repeats (1–16) Default: 2. */
    repeats?: number;
    /** Plank length : width (2–8) Default: 4. */
    ratio?: number;
    /** Ring density (1–30) Default: 6. */
    rings?: number;
    /** Grain wobble (0–3) Default: 0.7. */
    wobble?: number;
    /** Light, mid, dark Default: ["#d9a86c","#b07a45","#7a4e2c"]. */
    colors?: ColorString[] | string;
    /** Seam (plank-width units) (0–0.3) Default: 0.06. */
    seam?: number;
    /** Plank tone variation (0–1) Default: 0.6. */
    variation?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 27. */
    seed?: number | string;
  };
  /** Leopard / cheetah / jaguar — Rosettes: broken irregular rings around each feature point with a darker, warmer centre (leopard), larger rosettes with inner dots (jaguar) or solid spots (cheetah). Fur ground with soft tonal drift. */
  'leopard': {
    /** Style Default: "leopard". */
    style?: "leopard" | "jaguar" | "cheetah";
    /** Rosettes across (2–48) Default: 6. */
    cells?: number;
    /** Ground, centre, spot Default: ["#d9a35b","#b97834","#1d140e"]. */
    colors?: ColorString[] | string;
    /** Irregularity (0–1) Default: 0.6. */
    irregularity?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 13. */
    seed?: number | string;
  };
  /** Giraffe — Warped Voronoi patches with mottled interiors separated by a cream network of even width (exact Voronoi edge distance). */
  'giraffe': {
    /** Patches across (2–48) Default: 5. */
    cells?: number;
    /** Border width (0.02–0.5) Default: 0.12. */
    border?: number;
    /** Network, patch colours… Default: ["#f1e3c6","#8a4b1f","#6e3a17","#a35d2a"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 14. */
    seed?: number | string;
  };
  /** Zebra / tiger stripes — Noise-displaced, thickness-modulated stripes that fork and taper; tiger style adds broken stripe ends over an orange-to-cream fur ground. */
  'zebra': {
    /** Style Default: "zebra". */
    style?: "zebra" | "tiger";
    /** Stripes (1–64) Default: 9. */
    stripes?: number;
    /** Warp (0–2) Default: 0.6. */
    warpAmount?: number;
    /** Ground, stripe Default: ["#f5f2ea","#141414"]. */
    colors?: ColorString[] | string;
    /** Tiger fur colour Default: "#e08a2e". */
    tigerColor?: ColorString;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 15. */
    seed?: number | string;
  };
  /** Snakeskin (python / croc) — Python: overlapping diamond scales, each domed and edged, under large blotch markings. Croc: rows of glossy domed rectangular scales of varying width with deep creases. */
  'snakeskin': {
    /** Style Default: "python". */
    style?: "python" | "croc";
    /** Scales across (4–96) Default: 20. */
    cells?: number;
    /** Light, mid, markings Default: ["#cfc3a8","#8d7c5e","#3a2f22"]. */
    colors?: ColorString[] | string;
    /** Markings (0–1) Default: 0.85. */
    markings?: number;
    /** Gloss (0–1) Default: 0.4. */
    gloss?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 29. */
    seed?: number | string;
  };
  /** Camouflage — Woodland (layered thresholded fbm blobs with slightly ragged edges), digital (same field quantised to a pixel grid) or tiger-stripe camo (horizontal brush strokes). */
  'camouflage': {
    /** Style Default: "woodland". */
    style?: "woodland" | "digital" | "tiger-stripe";
    /** Blob frequency (1–16) Default: 3. */
    scale?: number;
    /** Digital grid (8–256) Default: 64. */
    pixels?: number;
    /** Base + layers Default: ["#7d7a52","#4b5b33","#6b4b2e","#1f1f1a"]. */
    colors?: ColorString[] | string;
    /** Layer coverage (0.2–0.8) Default: 0.5. */
    coverage?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 16. */
    seed?: number | string;
  };
  /** Reaction–diffusion (Gray–Scott) — Turing patterns from the Gray–Scott model on a periodic grid (seamless by construction), sampled with smooth bicubic filtering. Presets: coral, mitosis, maze, spots, worms, holes. Cost ∝ grid² × iterations; results are cached. */
  'reaction-diffusion': {
    /** Preset Default: "coral". */
    preset?: "coral" | "mitosis" | "maze" | "spots" | "worms" | "holes" | "custom";
    /** Feed (custom) (0.01–0.1) Default: 0.0545. */
    feed?: number;
    /** Kill (custom) (0.04–0.075) Default: 0.062. */
    kill?: number;
    /** Simulation grid (48–512) — Bigger = more, smaller features per tile (slower). Default: 160. */
    grid?: number;
    /** Iterations (200–30000) Default: 5000. */
    iterations?: number;
    /** Colour ramp Default: ["#0b132b","#5bc0be","#f7f7f2"]. */
    colors?: ColorString[] | string;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 17. */
    seed?: number | string;
  };
  /** Voronoi cells (stained glass / cracked earth / cobblestone) — Voronoi cells with EXACT border distance (even-width leading/grout/cracks). Stained glass with lead came and glass mottling, cracked earth with ragged cracks, domed cobblestones, or flat cells. */
  'voronoi-cells': {
    /** Style Default: "stained-glass". */
    style?: "stained-glass" | "cracked-earth" | "cobblestone" | "cells";
    /** Cells across (2–96) Default: 8. */
    cells?: number;
    /** Jitter (0–1) Default: 1. */
    jitter?: number;
    /** Edge width (cell units) (0–0.5) Default: 0.08. */
    edge?: number;
    /** Cell colours Default: ["#ff5d8f","#ffd166","#06d6a0","#118ab2","#f8f9fa"]. */
    colors?: ColorString[] | string;
    /** Edge colour Default: "#151515". */
    edgeColor?: ColorString;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 18. */
    seed?: number | string;
  };
  /** Leather grain — Pebbled full-grain leather: irregular rounded pebbles at two scales separated by fine creases, wandering wrinkles, pores, tonal mottling and a soft sheen, lit from the real height field. Pair output=normal for 3D. */
  'leather': {
    /** Colour Default: "#5a3522". */
    color?: ColorString;
    /** Grain density (8–160) Default: 40. */
    cells?: number;
    /** Crease depth (0–1) Default: 0.8. */
    crease?: number;
    /** Wrinkles (0–1) Default: 0.5. */
    wrinkles?: number;
    /** Sheen (0–1) Default: 0.3. */
    sheen?: number;
    /** Seed — Same seed + params = identical output, always. Change it for a different random variation. Default: 19. */
    seed?: number | string;
  };
}

export type PatternId = keyof PatternParams;
export type Category = 'woven' | 'knit' | 'textile' | 'geometric' | 'organic';
export type PresetId =
  | 'chambray'
  | 'linen'
  | 'canvas'
  | 'oxford-cloth'
  | 'gabardine'
  | 'chino'
  | 'twill-3-1-s'
  | 'silk-satin'
  | 'satin-weft-face'
  | 'dogtooth-large'
  | 'puppytooth'
  | 'houndstooth-print'
  | 'herringbone-tweed'
  | 'herringbone-draft'
  | 'sharkskin-navy'
  | 'prince-of-wales-brown'
  | 'gingham-navy'
  | 'gingham-print'
  | 'tartan-black-watch'
  | 'tartan-red-stewart'
  | 'buffalo-check'
  | 'flannel-plaid'
  | 'camel-check'
  | 'madras'
  | 'tartan-custom-hex'
  | 'raw-denim'
  | 'stonewash-denim'
  | 'donegal-grey'
  | 'harris-herringbone'
  | 'waffle-weave'
  | 'birdseye'
  | 'diamond-twill'
  | 'rib-2x2-navy'
  | 'seed-stitch'
  | 'garter-stitch'
  | 'knit-basketweave'
  | 'diamond-brocade'
  | 'fine-jersey'
  | 'nordic-snowflake'
  | 'christmas-trees'
  | 'fair-isle-hearts'
  | 'aran-sweater'
  | 'braid-cable'
  | 'chunky-cable-seed'
  | 'needlecord'
  | 'wide-wale-cord'
  | 'crushed-velvet-emerald'
  | 'velvet-midnight'
  | 'puffer-channel'
  | 'quilted-satin-blush'
  | 'fishnet'
  | 'tulle-white'
  | 'sequins-silver'
  | 'sequins-rainbow'
  | 'cross-stitch-flower'
  | 'cross-stitch-strawberry'
  | 'eyelet-see-through'
  | 'shibori-arashi'
  | 'shibori-kumo'
  | 'tie-dye-spiral'
  | 'breton'
  | 'pinstripe'
  | 'awning'
  | 'retro-diagonal'
  | 'wavy-candy'
  | 'harlequin'
  | 'racing-check'
  | 'ditsy-floral'
  | 'tossed-stars'
  | 'hearts-brick'
  | 'rain-drops'
  | 'falling-leaves'
  | 'polka-transparent'
  | 'missoni-zigzag'
  | 'argyle-golf'
  | 'honeycomb-bevel'
  | 'truchet-maze'
  | 'truchet-triangles'
  | 'seigaiha-red'
  | 'moroccan-ogee'
  | 'islamic-six-star'
  | 'islamic-square-60'
  | 'terrazzo-pastel'
  | 'halftone-lines'
  | 'halftone-radial'
  | 'contour-hypsometric'
  | 'subway-tiles'
  | 'brick-basketweave'
  | 'flemish-bond'
  | 'graph-paper'
  | 'dot-grid'
  | 'blueprint'
  | 'isometric-grid'
  | 'ridged-terrain'
  | 'warped-sunset'
  | 'clouds'
  | 'carrara'
  | 'calacatta-gold'
  | 'nero-marquina'
  | 'verde-marble'
  | 'black-galaxy-granite'
  | 'oak-floor'
  | 'walnut'
  | 'whitewashed-pine'
  | 'parquet-chevron'
  | 'parquet-basket'
  | 'cheetah'
  | 'jaguar'
  | 'snow-leopard'
  | 'tiger'
  | 'python'
  | 'croc-embossed'
  | 'camo-digital'
  | 'camo-desert'
  | 'camo-tiger-stripe'
  | 'camo-urban'
  | 'rd-mitosis'
  | 'rd-maze'
  | 'rd-worms'
  | 'cracked-earth'
  | 'cobblestone'
  | 'black-leather'
  | 'tan-leather';
