// Named looks ("presets"): a pattern id + a partial param set. Apps can show these as a one-click
// gallery: render(preset.pattern, { preset: preset.id }) or render(id, { params: preset.params }).
// Params not listed keep the pattern's defaults. Every preset is rendered by the test suite.
//
// Preset ids are globally unique, kebab-case, and stable (treat renames as breaking changes).

const pr = (id, pattern, name, params, tags = []) => ({ id, pattern, name, params, tags });

export const PRESETS = [
  // woven
  pr('chambray', 'plain-weave', 'Chambray', { warp: '#4f6d9a', weft: '#eef1f4', repeats: 24, heather: 0.15 }, ['shirt']),
  pr('linen', 'plain-weave', 'Natural linen', { warp: '#cbbd9f', weft: '#d9ccb0', repeats: 22, slub: 0.75, heather: 0.45, irregularity: 0.6, yarnGap: 0.16 }, ['summer']),
  pr('canvas', 'plain-weave', 'Canvas / duck', { warp: '#c8b48a', weft: '#bba57a', repeats: 14, yarnGap: 0.05, twist: 0.6 }, ['bag', 'workwear']),
  pr('oxford-cloth', 'basket-weave', 'Oxford shirting', { warp: '#7da3d6', weft: '#f4f4f0', group: 2, repeats: 14 }, ['shirt']),
  pr('gabardine', 'twill', 'Gabardine', { over: 2, under: 2, warp: '#5d5446', weft: '#6a604f', repeats: 20 }, ['coat']),
  pr('chino', 'twill', 'Chino drill', { over: 2, under: 1, warp: '#c2a878', weft: '#d6c6a2', repeats: 16 }, ['trousers']),
  pr('twill-3-1-s', 'twill', '3/1 S-twill', { over: 3, under: 1, direction: 'S', warp: '#5c3c2e', weft: '#e6d5b8' }),
  pr('silk-satin', 'satin', 'Silk satin', { shafts: 8, warp: '#c9a46b', weft: '#a8834c', sheen: 0.85, repeats: 10 }, ['luxury']),
  pr('satin-weft-face', 'satin', 'Sateen (weft-faced)', { shafts: 8, face: 'weft', warp: '#0f3b57', weft: '#c8d9e6' }),
  pr('dogtooth-large', 'houndstooth', 'Large dogtooth', { band: 8, repeats: 2 }),
  pr('puppytooth', 'houndstooth', 'Puppytooth (red)', { band: 2, repeats: 8, colors: ['#7b1113', '#efe6d8'] }),
  pr('houndstooth-print', 'houndstooth', 'Houndstooth (flat print)', { style: 'flat', repeats: 3 }, ['print']),
  pr('herringbone-tweed', 'herringbone', 'Herringbone tweed', { warp: '#3b3a36', weft: '#9b9078', heather: 0.6, slub: 0.4, irregularity: 0.6, repeats: 4 }),
  pr('herringbone-draft', 'herringbone', 'Herringbone (draft view)', { style: 'draft', repeats: 4 }),
  pr('sharkskin-navy', 'pick-and-pick', 'Navy sharkskin', { colors: ['#1d2840', '#7c8aa6'] }, ['suiting']),
  pr('prince-of-wales-brown', 'glen-check', 'Prince of Wales (brown)', { colors: ['#4a3426', '#e6dccb'], overcheckColor: '#7d2a2a' }),
  pr('gingham-navy', 'gingham', 'Navy gingham', { colors: ['#1f3a68', '#ffffff'], band: 4, repeats: 6 }),
  pr('gingham-print', 'gingham', 'Gingham (flat print)', { style: 'flat', band: 8, repeats: 4 }, ['print']),
  pr('tartan-black-watch', 'tartan', 'Black Watch', { sett: 'black-watch' }),
  pr('tartan-red-stewart', 'tartan', 'Red Stewart-style', { sett: 'red-stewart-style', countScale: 0.6 }),
  pr('buffalo-check', 'tartan', 'Buffalo check', { sett: 'buffalo-check', countScale: 1, repeats: 2 }, ['lumberjack']),
  pr('flannel-plaid', 'tartan', 'Brushed flannel plaid', { sett: 'four-colour', countScale: 1, fuzz: 0.55 }, ['flannel']),
  pr('camel-check', 'tartan', 'Camel check-style', { sett: 'camel-check-style', countScale: 1.2 }),
  pr('madras', 'tartan', 'Madras', { sett: 'madras-style', symmetric: false, countScale: 1, yarnGap: 0.1, irregularity: 0.5 }, ['summer']),
  pr('tartan-custom-hex', 'tartan', 'Custom hex sett', { sett: 'custom', threadcount: '#2d3047/24 #e0a458/4 #2d3047/8 #93b7be/16', countScale: 1 }),
  pr('raw-denim', 'denim', 'Raw selvedge denim', { indigo: '#16264a', wash: 0, irregularity: 0.85, slub: 0.5 }, ['jeans']),
  pr('stonewash-denim', 'denim', 'Stonewashed denim', { indigo: '#3a5a8c', wash: 0.85 }, ['jeans']),
  pr('donegal-grey', 'tweed', 'Donegal grey', { warp: '#6b6a66', weft: '#8d8a82', neps: 0.55 }),
  pr('harris-herringbone', 'tweed', 'Harris herringbone', { weave: 'herringbone', warp: '#4b4a33', weft: '#7b6b4a', neps: 0.3, nepColors: ['#a33b2a', '#d8b26e', '#3d6b6b'] }),
  pr('waffle-weave', 'weave-draft', 'Waffle / honeycomb', { draft: '11111111/10000001/10111101/10100101/10100101/10111101/10000001/11111111', warpColors: ['#efe9df'], warpCounts: '1', weftColors: ['#e3dccf'], weftCounts: '1', repeats: 4, yarnGap: 0.18 }, ['towel']),
  pr('birdseye', 'weave-draft', "Bird's-eye", { draft: '0110/1001/1001/0110', warpColors: ['#2b3440', '#c9ced6'], warpCounts: '1 1', weftColors: ['#2b3440', '#c9ced6'], weftCounts: '1 1', repeats: 10 }, ['suiting']),
  pr('diamond-twill', 'weave-draft', 'Diamond twill', { draft: '11000011/10000111/00001111/00011110/00111100/01111000/11110000/11100001', warpColors: ['#5b2a3c'], warpCounts: '1', weftColors: ['#e4cfa8'], weftCounts: '1', repeats: 5 }),

  // knit
  pr('rib-2x2-navy', 'knit', '2×2 rib (navy)', { stitch: 'rib-2x2', color: '#2f4858' }, ['beanie', 'cuffs']),
  pr('seed-stitch', 'knit', 'Seed stitch', { stitch: 'seed', color: '#6c8e54' }),
  pr('garter-stitch', 'knit', 'Garter stitch', { stitch: 'garter', color: '#c97b63' }),
  pr('knit-basketweave', 'knit', 'Knit basketweave', { stitch: 'basketweave', color: '#c9a66b', stitchesAcross: 24 }),
  pr('diamond-brocade', 'knit', 'Diamond brocade', { stitch: 'diamond-brocade', color: '#2f6f73', stitchesAcross: 24 }),
  pr('fine-jersey', 'knit', 'Fine jersey (t-shirt)', { stitch: 'stockinette', color: '#3c3c44', stitchesAcross: 48, yarnRadius: 0.27, fuzz: 0.2 }),
  pr('nordic-snowflake', 'fair-isle', 'Nordic snowflake', { chart: 'snowflake', colors: ['#20304a', '#f4f1e8'], stitchesAcross: 27 }, ['christmas']),
  pr('christmas-trees', 'fair-isle', 'Christmas trees', { chart: 'trees', colors: ['#a4161a', '#f5f3f4', '#5c4033'], stitchesAcross: 20 }, ['christmas']),
  pr('fair-isle-hearts', 'fair-isle', 'Hearts', { chart: 'hearts', colors: ['#f6e8ea', '#c9184a'], stitchesAcross: 20 }),
  pr('aran-sweater', 'cable-knit', 'Aran sweater', { cable: 'mixed', stitchesAcross: 40, color: '#ece3cf' }),
  pr('braid-cable', 'cable-knit', 'Braided cable', { cable: 'braid', stitchesAcross: 30, color: '#8c9a7e' }),
  pr('chunky-cable-seed', 'cable-knit', 'Chunky cable on seed', { ground: 'seed', stitchesAcross: 18, color: '#d6c7b0', yarnRadius: 0.3 }),

  // textile
  pr('needlecord', 'corduroy', 'Needlecord', { wales: 28, color: '#6b3b2a' }),
  pr('wide-wale-cord', 'corduroy', 'Wide-wale cord', { wales: 7, color: '#b38b4d', groove: 0.15 }),
  pr('crushed-velvet-emerald', 'velvet', 'Crushed velvet (emerald)', { color: '#0f5132', crush: 0.85 }),
  pr('velvet-midnight', 'velvet', 'Midnight velvet', { color: '#1b1f3b', crush: 0.35, sheen: 0.8 }),
  pr('puffer-channel', 'quilted', 'Puffer jacket', { layout: 'channel', cells: 6, color: '#7a8b5c' }, ['puffer']),
  pr('quilted-satin-blush', 'quilted', 'Quilted satin', { surface: 'satin', color: '#e8b4b8', stitch: '#f4dfe0', cells: 5 }),
  pr('fishnet', 'mesh', 'Fishnet (see-through)', { backing: 'transparent', cells: 8 }),
  pr('tulle-white', 'mesh', 'White tulle', { layout: 'hex', cells: 12, yarn: 0.06, color: '#f5f5f5', backing: '#2b2d42' }),
  pr('sequins-silver', 'sequins', 'Silver sequins', { colors: ['#b8bcc4'], cells: 14 }),
  pr('sequins-rainbow', 'sequins', 'Rainbow sequins', { colors: ['#e63946', '#f4a261', '#e9c46a', '#2a9d8f', '#457b9d', '#9b5de5'], cells: 16 }),
  pr('cross-stitch-flower', 'cross-stitch', 'Folk flower', { chart: 'flower', repeats: 3 }),
  pr('cross-stitch-strawberry', 'cross-stitch', 'Strawberries', { chart: 'strawberry', repeats: 3, colors: ['#c1121f', '#2d6a4f', '#386641', '#fefae0'] }),
  pr('eyelet-see-through', 'eyelet-lace', 'Eyelet (see-through)', { backing: 'transparent' }),
  pr('shibori-arashi', 'shibori', 'Arashi', { style: 'arashi' }),
  pr('shibori-kumo', 'shibori', 'Kumo', { style: 'kumo' }),
  pr('tie-dye-spiral', 'shibori', 'Tie-dye spiral', { style: 'spiral', cells: 2, colors: ['#7b2cbf', '#fff3b0'] }),

  // geometric
  pr('breton', 'stripes', 'Breton stripe', { colors: ['#1b2a49', '#f4f1ea'], widths: '1 1.6', repeats: 14 }),
  pr('pinstripe', 'stripes', 'Pinstripe', { colors: ['#e8e6e1', '#22262e'], widths: '1 16', direction: 'vertical', repeats: 12 }),
  pr('awning', 'stripes', 'Awning stripe', { colors: ['#d62828', '#fdf0d5'], widths: '1 1', direction: 'vertical', repeats: 6 }),
  pr('retro-diagonal', 'stripes', 'Retro diagonal', { colors: ['#f4a259', '#5b8e7d', '#f4e285', '#bc4b51'], widths: '3 2 1 2', direction: 'diagonal', repeats: 4 }),
  pr('wavy-candy', 'stripes', 'Wavy candy stripe', { colors: ['#ffcdb2', '#e5989b', '#6d6875'], wave: 0.35, waveFreq: 3, repeats: 6 }),
  pr('harlequin', 'checkerboard', 'Harlequin', { diagonal: true, colors: ['#1d1d1d', '#c1121f'], cells: 6 }),
  pr('racing-check', 'checkerboard', 'Racing check', { cells: 16 }),
  pr('ditsy-floral', 'dots', 'Ditsy floral', { layout: 'tossed', shape: 'flower', rotate: true, sizeJitter: 0.5, size: 0.32, cells: 7, colors: ['#f28482', '#f6bd60', '#84a59d'], background: '#f7ede2', centerColor: '#ffd166' }, ['floral']),
  pr('tossed-stars', 'dots', 'Tossed stars', { layout: 'tossed', shape: 'star', rotate: true, sizeJitter: 0.6, size: 0.3, colors: ['#ffb703', '#fb8500', '#219ebc'], background: '#023047', cells: 9 }),
  pr('hearts-brick', 'dots', 'Hearts', { layout: 'brick', shape: 'heart', size: 0.3, colors: ['#e5383b'], background: '#ffe5ec' }),
  pr('rain-drops', 'dots', 'Raindrops', { layout: 'half-drop', shape: 'teardrop', colors: ['#3d405b'], size: 0.26 }),
  pr('falling-leaves', 'dots', 'Falling leaves', { layout: 'tossed', shape: 'leaf', rotate: true, colors: ['#2d6a4f', '#40916c', '#74c69d'], background: '#fefae0', cells: 8 }),
  pr('polka-transparent', 'dots', 'Polka dots (transparent)', { background: 'transparent', colors: ['#111111'], layout: 'half-drop' }),
  pr('missoni-zigzag', 'chevron', 'Missoni zigzag', { colors: ['#3d2c8d', '#916bbf', '#c996cc', '#f9f871', '#ff6f91'], bands: 15, zigs: 8, amplitude: 2 }),
  pr('argyle-golf', 'argyle', 'Golf argyle', { colors: ['#1b4332', '#d8f3dc', '#95d5b2'], lineColor: '#081c15', dashed: true }),
  pr('honeycomb-bevel', 'honeycomb', 'Bevelled hex tiles', { style: 'bevel', colors: ['#3a86ff', '#4895ef', '#4361ee'], background: '#0b0f2a' }),
  pr('truchet-maze', 'truchet', '10-PRINT maze', { variant: 'maze', cells: 16, colors: ['#111111', '#f5f0e6', '#111111'], lineWidth: 0.12 }),
  pr('truchet-triangles', 'truchet', 'Triangle tiles', { variant: 'triangles', cells: 8, lineWidth: 0, colors: ['#f6bd60', '#84a59d', '#000000'] }),
  pr('seigaiha-red', 'seigaiha', 'Seigaiha (vermilion)', { colors: ['#c1121f', '#fdf0d5', '#e76f51', '#fdf0d5'], outlineColor: '#780000' }),
  pr('moroccan-ogee', 'ogee', 'Moroccan ogee', { colors: ['#f1faee', '#a8dadc'], lineColor: '#1d3557', dot: 0.06 }),
  pr('islamic-six-star', 'islamic-star', 'Six-point stars', { tiling: '6.6.6', angle: 55, repeats: 2, colors: ['#1d3557', '#e9c46a', '#14213d'] }),
  pr('islamic-square-60', 'islamic-star', 'Square Hankin 60°', { tiling: '4.4.4.4', angle: 60, repeats: 4, colors: ['#f2e9dc', '#8c2f39', '#461220'] }),
  pr('terrazzo-pastel', 'terrazzo', 'Pastel terrazzo', { background: '#f7f3ee', colors: ['#f4acb7', '#9d8189', '#ffcad4', '#d8e2dc', '#ffe5d9'] }),
  pr('halftone-lines', 'halftone', 'Line screen', { dot: 'line', field: 'waves', colors: ['#fdf0d5', '#003049'] }),
  pr('halftone-radial', 'halftone', 'Radial halftone', { field: 'radial', scale: 2, colors: ['#ffffff', '#111111'], cells: 32 }),
  pr('contour-hypsometric', 'contour-lines', 'Hypsometric map', { fill: true, colors: ['#ffffff', '#3d2b1f'] }),
  pr('subway-tiles', 'bricks', 'Subway tiles', { bond: 'running', cols: 6, rows: 14, colors: ['#f4f4f2', '#ecebe7', '#f8f8f6'], mortarColor: '#9aa0a6', roughness: 0.15, chipping: 0 }),
  pr('brick-basketweave', 'bricks', 'Basket-weave pavers', { bond: 'basket', cols: 4, rows: 8 }),
  pr('flemish-bond', 'bricks', 'Flemish bond', { bond: 'flemish', cols: 4, rows: 10 }),
  pr('graph-paper', 'grid-paper', 'Graph paper', { style: 'lines' }),
  pr('dot-grid', 'grid-paper', 'Dot grid', { style: 'dots', cells: 24, majorEvery: 0, colors: ['#fbfaf7', '#8c8c8c', '#8c8c8c'] }),
  pr('blueprint', 'grid-paper', 'Blueprint', { colors: ['#1e4f8a', '#4f7fb8', '#d6e4f5'], cells: 20, majorEvery: 5 }),
  pr('isometric-grid', 'grid-paper', 'Isometric grid', { style: 'isometric', majorEvery: 0 }),

  // organic
  pr('ridged-terrain', 'noise', 'Ridged terrain', { mode: 'ridged', colors: ['#1b4332', '#52b788', '#d8f3dc', '#ffffff'], frequency: 3 }),
  pr('warped-sunset', 'noise', 'Warped sunset', { warp: 1, colors: ['#2d1e2f', '#7b2d43', '#e05e3c', '#f7b267', '#fef3e2'], frequency: 2 }),
  pr('clouds', 'noise', 'Clouds', { colors: ['#4a90d9', '#ffffff'], contrast: 1.6, frequency: 3 }),
  pr('carrara', 'marble', 'Carrara', { base: '#efeeea', vein: '#8a8d91', tint: '#dcdcdc', accent: '#b9bcc0', sharpness: 4 }),
  pr('calacatta-gold', 'marble', 'Calacatta gold', { base: '#f4f1ea', vein: '#4a4038', accent: '#c9a45c', veins: 1, turbulence: 1.4, sharpness: 6, fine: 0.3 }),
  pr('nero-marquina', 'marble', 'Nero Marquina', { base: '#151515', vein: '#efefef', tint: '#2a2a2a', accent: '#555555', veins: 2, turbulence: 1.4 }),
  pr('verde-marble', 'marble', 'Verde marble', { base: '#1f3d2b', vein: '#d8e8d0', tint: '#2f5a3f', accent: '#5f8f6a', veins: 2, turbulence: 2 }),
  pr('black-galaxy-granite', 'granite', 'Black granite', { colors: ['#1c1c1e', '#2c2c2e', '#5a5a5e', '#c9a45c'], glints: 0.7 }),
  pr('oak-floor', 'wood', 'Oak floor', { colors: ['#d8b58a', '#b88b5e', '#8a6240'], planks: 5, rings: 12 }),
  pr('walnut', 'wood', 'Walnut', { colors: ['#8b5e3c', '#5d3a22', '#3b2314'], planks: 4, knots: 0.35 }),
  pr('whitewashed-pine', 'wood', 'Whitewashed pine', { colors: ['#efe6d8', '#d9c7ad', '#b59c7d'], planks: 6, knots: 0.5 }),
  pr('parquet-chevron', 'parquet', 'Chevron parquet', { layout: 'chevron' }),
  pr('parquet-basket', 'parquet', 'Basket parquet', { layout: 'basket', repeats: 3 }),
  pr('cheetah', 'leopard', 'Cheetah', { style: 'cheetah' }),
  pr('jaguar', 'leopard', 'Jaguar', { style: 'jaguar', cells: 5 }),
  pr('snow-leopard', 'leopard', 'Snow leopard', { colors: ['#e9e6df', '#cfc9bd', '#3b3a38'] }),
  pr('tiger', 'zebra', 'Tiger', { style: 'tiger' }),
  pr('python', 'snakeskin', 'Python', { cells: 24, colors: ['#e8e2d0', '#b9a77f', '#2a241c'] }),
  pr('croc-embossed', 'snakeskin', 'Croc embossed', { style: 'croc', colors: ['#3f4a2f', '#2b3320', '#141a10'], cells: 12, gloss: 0.7 }),
  pr('camo-digital', 'camouflage', 'Digital camo', { style: 'digital', colors: ['#c2b280', '#8b7d5b', '#5e5340', '#3a3226'] }),
  pr('camo-desert', 'camouflage', 'Desert camo', { colors: ['#d8c49a', '#b89b6a', '#8c6d46', '#5a4630'] }),
  pr('camo-tiger-stripe', 'camouflage', 'Tiger-stripe camo', { style: 'tiger-stripe', colors: ['#9c9a6a', '#4d5b33', '#1e2016'] }),
  pr('camo-urban', 'camouflage', 'Urban camo', { colors: ['#d9d9d9', '#9e9e9e', '#5e5e5e', '#262626'] }),
  pr('rd-mitosis', 'reaction-diffusion', 'Mitosis', { regime: 'mitosis', colors: ['#fff8f0', '#f08080', '#6b2737'] }),
  pr('rd-maze', 'reaction-diffusion', 'Turing maze', { regime: 'maze', colors: ['#111111', '#eeeeee'] }),
  pr('rd-worms', 'reaction-diffusion', 'Worms', { regime: 'worms', colors: ['#14213d', '#fca311', '#e5e5e5'] }),
  pr('cracked-earth', 'voronoi-cells', 'Cracked earth', { style: 'cracked-earth', colors: ['#b5835a', '#a87449', '#c4935f'], edgeColor: '#3b2a1d', edge: 0.06, cells: 7 }),
  pr('cobblestone', 'voronoi-cells', 'Cobblestones', { style: 'cobblestone', colors: ['#8d8d8d', '#7a7a7a', '#a39e93'], edgeColor: '#2b2b2b', cells: 6, edge: 0.12 }),
  pr('black-leather', 'leather', 'Black leather', { color: '#1d1c1c', sheen: 0.5 }),
  pr('tan-leather', 'leather', 'Tan saddle leather', { color: '#9a5b2e', cells: 28, crease: 0.6 }),
];
